# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - transcoder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ac99aac7327d4099b7bd9736800a3e1a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_565e8d93e35147168f77c8967d23194b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ac99aac7327d4099b7bd9736800a3e1a }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'transcoder'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_70b45fe83be1492f8753247b62f2244a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ac99aac7327d4099b7bd9736800a3e1a }}/appsvc/staticsite:${{ github.sha }}'